### ISSUE TITLE
[PaddleV3] x2paddle 套件能力建设 Tracking Issue

### ISSUE THREAD

**Issue by megemini** [PaddlePaddle/X2Paddle#1060]
### x2paddle 套件能力建设

X2Paddle 是飞桨生态下的模型转换工具，致力于帮助其它深度学习框架（Caffe/TensorFlow/ONNX/PyTorch）用户快速迁移至飞桨框架。由于近期 Paddle 新版本的升级存在不兼容部分（如 paddle.fluid API 全面退场，0-d tensor，view 行为修改等），需要重新对 X2Paddle 进行适配开发与回归测试，保证模型转换工具的正常运转，转换后模型的功能与精度不受损失。同时，近期大模型领域有新的热门模型发布，需要添加此类模型的转换策略，保证模型转换工具的丰富度和领先性。

更多信息参考 [x2paddle 套件能力建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_7th/%E3%80%90Hackathon%207th%E3%80%91FundableProject%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#%E4%B8%89x2paddle-%E5%A5%97%E4%BB%B6%E8%83%BD%E5%8A%9B%E5%BB%BA%E8%AE%BE)

### RFC

* [x] https://github.com/PaddlePaddle/community/pull/971

### 🏗️ 第一阶段 适配 Paddle 3.0.0

* [x] 1-1. 升级 CI 环境
  https://github.com/PaddlePaddle/X2Paddle/pull/1061
   https://github.com/PaddlePaddle/X2Paddle/pull/1064
* [x] 1-2. 修复 `paddle.fluid` 兼容问题
  https://github.com/PaddlePaddle/X2Paddle/issues/1059
* [x] 1-3. 修复其他兼容性问题
  https://github.com/PaddlePaddle/X2Paddle/issues/1066
* [x] 1-4. 使用新的动转静
  https://github.com/PaddlePaddle/X2Paddle/pull/1093
* [x] 1.5. 英文说明文档
  https://github.com/PaddlePaddle/X2Paddle/pull/1101

### 🔜 第二阶段 补充模型

* [x] 2-1. 新增 1-2 个大语言模型的转换策略
  https://github.com/PaddlePaddle/X2Paddle/pull/1085
  https://github.com/PaddlePaddle/X2Paddle/pull/1086
  https://github.com/PaddlePaddle/X2Paddle/pull/1099

### 🔜 第三阶段 收尾

* [ ] 3-1. 任务总结，PPT，答辩
* [x] 3-2. 清理 test_autoscan 的日志 `logger.xxx`
  https://github.com/PaddlePaddle/X2Paddle/pull/1103
* [ ] 3-3. 更新 dockerfile
* [x] 3-4. 更新 [x2paddle_model_zoo.md](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/introduction/x2paddle_model_zoo.md) & 首页 ReadME
  https://github.com/PaddlePaddle/X2Paddle/pull/1103
  https://github.com/PaddlePaddle/X2Paddle/pull/1101
* [ ] 3-5. 出 x2paddle 新版本
### 其他
* [ ] 跟踪 tf 两个模型的问题，需要 Paddle 主框架配合
  - https://github.com/PaddlePaddle/X2Paddle/pull/1083
  - https://github.com/PaddlePaddle/X2Paddle/pull/1091
* [ ] 跟踪 inference 卡住的问题
  https://github.com/PaddlePaddle/X2Paddle/pull/1077

@luotao1 

请悉知～ ：）
